# Generated by Django 5.1.2 on 2024-10-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(choices=[('gaming', 'Gaming'), ('ultrabook', 'Ultrabook'), ('business', 'Business'), ('2-in-1', '2-in-1 Convertible'), ('student', 'Student'), ('workstation', 'Workstation')], max_length=20, null=True)),
                ('ram', models.CharField(max_length=50, null=True)),
                ('rom', models.CharField(max_length=50, null=True)),
                ('cpu', models.CharField(max_length=50, null=True)),
                ('gpu', models.CharField(max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('size_battery', models.CharField(max_length=50, null=True)),
                ('size_monitor', models.CharField(max_length=50, null=True)),
                ('camera', models.CharField(max_length=50, null=True)),
                ('fingerprint', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('shipped', 'Shipped'), ('processing', 'Processing')], default='pending', max_length=20)),
            ],
        ),
    ]
