# Generated by Django 5.1.2 on 2024-10-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopstore', '0002_laptop_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Coustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laptopstore.coustomer'),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laptopstore.laptop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('shipped', 'Shipped'), ('processing', 'Processing')], max_length=20, null=True),
        ),
    ]
