# Generated by Django 5.1.2 on 2024-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopstore', '0003_tag_order_coustomer_order_laptop_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Tag',
            field=models.ManyToManyField(to='laptopstore.tag'),
        ),
    ]
