# Generated by Django 5.1.2 on 2024-10-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopstore', '0004_order_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='Tag',
            field=models.ManyToManyField(to='laptopstore.tag'),
        ),
    ]
