# Generated by Django 5.1.2 on 2024-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopstore', '0005_laptop_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Shipped', 'Shipped'), ('Processing', 'Processing')], max_length=20, null=True),
        ),
    ]
