# Generated by Django 5.1.2 on 2024-11-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopstore', '0007_coustomer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
