# Generated by Django 5.1.2 on 2024-11-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopstore', '0008_coustomer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to=''),
        ),
    ]
