# Generated by Django 5.1.2 on 2024-11-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopstore', '0017_alter_coustomer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_images/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_images/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_images/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_images/'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='laptop_images/'),
        ),
    ]
